services:
  - type: web
    name: trad1k3-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

  - type: worker
    name: sales-updater
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c "while true; do python update_sales.py; sleep 3600; done"